<?php

/**
 * Implements hook_block_info()
 */
function hello_block_info() {
  $blocks = [
    'hello_world' => [
      'info' => t('Hello World Block'),
    ],
    'hello_user' => [
      'info' => t('Hello User Block'),
    ],
    'user_info' => [
      'info' => t('User Info Block'),
    ],
  ];

  return $blocks;
}

/**
 * Implements hook_block_view()
 */
function hello_block_view($delta = '') {
  $block = [];

  switch ($delta) {
    case 'hello_world':
      $block['subject'] = t('Hello World!!!');
      $block['content'] = t('This is the hello world block.');
      break;

    case 'hello_user':
      $hour = date('G');
      $greeting = 'Good Evening @name!';
      if ($hour < 12) {
        $greeting = 'Good Morning @name!';
      }
      elseif ($hour < 18) {
        $greeting = 'Good Afternoon @name!';
      }

      $block['subject'] = t('Hello World');
      $block['content'] = t($greeting, ['@name' => $GLOBALS['user']->name]);
      break;

    case 'user_info':
      if (arg(0) == 'user' && is_numeric(arg(1))) {
        $this_user = user_load(arg(1));
        if (!empty($this_user)) {
          $block['subject'] = t('User Info');

          // Common label value theme func.
          $theme_item = function($label, $value) {
            return '<div><label>' . t($label) . '</label>' . $value . '</div>';
          };

          $output = '';
          $output .= $theme_item('Name', $this_user->name);
          $output .= $theme_item('Email', $this_user->mail);
          $output .= $theme_item('Created', date('m/d/Y g:ia', $this_user->created));

          $access = ($this_user->access == 0) ? 'Never' : date('m/d/Y g:ia', $this_user->access);
          $output .= $theme_item('Last Accessed', $access);

          $block['content'] = $output;
        }
      }
      break;
  }

  return $block;
}