<?php

function even_nodes_views_query_alter(&$view, &$query) {
  if ($view->base_table == 'node') {
    // $query->add_where(1, 'node.nid', 20, '>');
    $query->add_where_expression(1, 'node.nid % 2 = 0');
  }
}

function even_nodes_views_pre_render(&$view) {
  if ($view->name == 'node_list') {
    foreach ($view->result as &$result) {
      $result->node_title = 'Title: ' . $result->node_title;
    }
  }
}

function even_nodes_views_post_render(&$view, &$output, &$cache) {
  if ($view->name == 'node_list') {
    $output = '<div style="background-color: #ff0;">' . $output . '</div>';
  }
}