<?php

/**
 * Implements hook_menu()
 */
function hello_menu_menu() {
  $items = [];

  $items['hello'] = [
    'title' => 'Hello World',
    'page callback' => 'hello_menu_simple_hello',
    'access arguments' => ['access content'],
    'menu_name' => 'main-menu',
    'weight' => 1,
  ];

  $items['variables'] = [
    'title' => 'System Variables',
    'page callback' => 'hello_menu_list_variables',
    'access arguments' => ['access content'],
    'menu_name' => 'main-menu',
    'weight' => 2,
  ];

  $items['variables/%'] = [
    'title callback' => 'hello_menu_show_variable_title',
    'title arguments' => [1],
    'page callback' => 'hello_menu_show_variable',
    'page arguments' => [1],
    'access arguments' => ['access content'],
    'menu_name' => 'main-menu',
    'weight' => 3,
  ];

  return $items;
}

function hello_menu_simple_hello() {
  return t('hello world simple');
}

function hello_menu_list_variables() {
  $vars = variable_initialize();
  $names = array_keys($vars);
  $output = '<ul>';

  foreach ($names as $name) {
    $output .= '<li>' . l($name, '/variables/' . $name, [
      'attributes' => ['target' => '_blank'],
    ]) . '</li>';
  }

  $output .= '</ul>';
  return $output;
}

function hello_menu_show_variable($name) {
  $var = variable_get($name, t('No Value Found'));
  return kpr($var, TRUE);
}

function hello_menu_show_variable_title($name) {
  return t('System Variable: @name', ['@name' => $name]);
}